version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin-volume:/var/lib/pgadmin
    depends_on:
      - db

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #   restart: unless-stopped
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - '8080:8080'
  #   networks:
  #     - default

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '80:3000'

volumes:
  db-volume:
  pgadmin-volume:
