export const QUERY_KEYS = {
  PROJECT: 'PROJECT',
  PROJECTS: 'PROJECTS',
  TASK_COLUMN: 'TASK_COLUMN',
  TASK_COLUMNS: 'TASK_COLUMNS',
  TASK: 'TASK',
  TASKS: 'TASKS',
  USER: 'USER',
  USERS: 'USERS',
} as const;
